FROM node:20-alpine

WORKDIR /usr/src/app

# Копируем package.json и yarn.lock для установки зависимостей
COPY package.json ./

RUN yarn install --frozen-lockfile

# Копируем весь исходный код
COPY . .

# Открываем порт приложения
EXPOSE 3000

# Запускаем приложение в режиме разработки с hot-reload
CMD ["yarn", "start:dev"]
