version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_app_dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: blogger-platform-dev
      JWT_SECRET_AT: 9116c387-31bb-4fff-8587-7fd1bd41215d
      JWT_SECRET_RT: babf4b6f-ba0b-473c-b02a-f86ff8706f85
      ADMIN_LOGIN: admin
      ADMIN_PASSWORD: qwerty
      EMAIL_APP: example@example.com
      EMAIL_APP_PASSWORD: 123
      SEND_INTERNAL_SERVER_ERROR_DETAILS: true
      INCLUDE_TESTING_MODULE: true
      IS_SWAGGER_ENABLED: true
      JWT_EXPIRATION_AT: 1m
      JWT_EXPIRATION_RT: 2m
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
